### ISSUE TITLE
Broken Satori Model

### ISSUE THREAD

**Issue by aeroracmas** [mumifaglalolanda/2hu-GTA#2]
![Screenshot (31)](https://user-images.githubusercontent.com/97804543/149647356-7d08500c-2a75-420b-b39d-10aafad29222.png)
The Satori in the banner looks beautiful! However, upon installing the latest common would end up with a broken model instead, as attached.

**Comment by lolipalooza** [comment]
Hello.

Sorry for the delayed response.

I don't know why she looks like that, but certainly is not the same Satori that appears in the banner because the files available for download are outdated.

If you want the banner models, you can get them from here:
https://1drv.ms/u/s!AqfCbp8i1mGyhYo2N5FDHG7_3niL1g
You'll find not only Satory but a LOT of beauty Touhou models that i took the time to convert by myself because of the lack of available Touhou skins for GTA. You'll find Satori as `satori_sama.dff` & `satori_sama.txd`

You'll have to replace them by yourself. If you don't know how, use `Alci's IMG Editor 1.5` and look how to use it. Remember all the skins that appear ingame are in the file `touhou.img`, so that's the file you'll have to open with the IMG editor.

Sadly, this project is totally frozen for now. I hope i can retake it in a future, but for now that future looks far away.

Hope you notice this response 😅

**Comment by aeroracmas** [comment]
Godspeed! exactly what I needed at the right time. thank you for your efforts you put into this project!
